name: "Create PR"
on:
  push:
    branches:
      - io
      - internal
jobs: 
  pull-request-for-test:
      runs-on: ubuntu-latest
      steps:       
      - name: run
        id: pr
        uses: emiliopedrollo/create-pull-request@v1.1.0
        with :
          base: test
          head: ${{ github.ref_name }}
          title: ${{ github.event.head_commit.id }}
          body: ${{ github.event.head_commit.message }}
          milestone: 1
          labels: patching
